// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trading.proto

package tradingdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ORDERTYPE int32

const (
	ORDERTYPE_INVALIDTYPE ORDERTYPE = 0
	ORDERTYPE_LIMIT       ORDERTYPE = 1
)

var ORDERTYPE_name = map[int32]string{
	0: "INVALIDTYPE",
	1: "LIMIT",
}
var ORDERTYPE_value = map[string]int32{
	"INVALIDTYPE": 0,
	"LIMIT":       1,
}

func (x ORDERTYPE) String() string {
	return proto.EnumName(ORDERTYPE_name, int32(x))
}
func (ORDERTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{0}
}

type ORDERSIDE int32

const (
	ORDERSIDE_INVALID_ORDERSIDE ORDERSIDE = 0
	ORDERSIDE_ORDER_BUY         ORDERSIDE = 1
	ORDERSIDE_ORDER_SELL        ORDERSIDE = 2
)

var ORDERSIDE_name = map[int32]string{
	0: "INVALID_ORDERSIDE",
	1: "ORDER_BUY",
	2: "ORDER_SELL",
}
var ORDERSIDE_value = map[string]int32{
	"INVALID_ORDERSIDE": 0,
	"ORDER_BUY":         1,
	"ORDER_SELL":        2,
}

func (x ORDERSIDE) String() string {
	return proto.EnumName(ORDERSIDE_name, int32(x))
}
func (ORDERSIDE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{1}
}

type TRADESIDE int32

const (
	TRADESIDE_INVALID_TRADESIDE TRADESIDE = 0
	TRADESIDE_TRADE_BUY         TRADESIDE = 1
	TRADESIDE_TRADE_SELL        TRADESIDE = 2
)

var TRADESIDE_name = map[int32]string{
	0: "INVALID_TRADESIDE",
	1: "TRADE_BUY",
	2: "TRADE_SELL",
}
var TRADESIDE_value = map[string]int32{
	"INVALID_TRADESIDE": 0,
	"TRADE_BUY":         1,
	"TRADE_SELL":        2,
}

func (x TRADESIDE) String() string {
	return proto.EnumName(TRADESIDE_name, int32(x))
}
func (TRADESIDE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{2}
}

type Candle struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Open                 int64    `protobuf:"varint,3,opt,name=open,proto3" json:"open,omitempty"`
	Close                int64    `protobuf:"varint,4,opt,name=close,proto3" json:"close,omitempty"`
	High                 int64    `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Low                  int64    `protobuf:"varint,6,opt,name=low,proto3" json:"low,omitempty"`
	CurTime              int64    `protobuf:"varint,7,opt,name=curTime,proto3" json:"curTime,omitempty"`
	Volume               int64    `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenInterest         int64    `protobuf:"varint,9,opt,name=openInterest,proto3" json:"openInterest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candle) Reset()         { *m = Candle{} }
func (m *Candle) String() string { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()    {}
func (*Candle) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{0}
}
func (m *Candle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candle.Unmarshal(m, b)
}
func (m *Candle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candle.Marshal(b, m, deterministic)
}
func (dst *Candle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candle.Merge(dst, src)
}
func (m *Candle) XXX_Size() int {
	return xxx_messageInfo_Candle.Size(m)
}
func (m *Candle) XXX_DiscardUnknown() {
	xxx_messageInfo_Candle.DiscardUnknown(m)
}

var xxx_messageInfo_Candle proto.InternalMessageInfo

func (m *Candle) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Candle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candle) GetOpen() int64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Candle) GetClose() int64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Candle) GetHigh() int64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Candle) GetLow() int64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Candle) GetCurTime() int64 {
	if m != nil {
		return m.CurTime
	}
	return 0
}

func (m *Candle) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Candle) GetOpenInterest() int64 {
	if m != nil {
		return m.OpenInterest
	}
	return 0
}

type CandleChunk struct {
	Code                 string    `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime            int64     `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64     `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	KeyID                string    `protobuf:"bytes,5,opt,name=keyID,proto3" json:"keyID,omitempty"`
	Candles              []*Candle `protobuf:"bytes,6,rep,name=candles,proto3" json:"candles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CandleChunk) Reset()         { *m = CandleChunk{} }
func (m *CandleChunk) String() string { return proto.CompactTextString(m) }
func (*CandleChunk) ProtoMessage()    {}
func (*CandleChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{1}
}
func (m *CandleChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandleChunk.Unmarshal(m, b)
}
func (m *CandleChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandleChunk.Marshal(b, m, deterministic)
}
func (dst *CandleChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandleChunk.Merge(dst, src)
}
func (m *CandleChunk) XXX_Size() int {
	return xxx_messageInfo_CandleChunk.Size(m)
}
func (m *CandleChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_CandleChunk.DiscardUnknown(m)
}

var xxx_messageInfo_CandleChunk proto.InternalMessageInfo

func (m *CandleChunk) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CandleChunk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CandleChunk) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CandleChunk) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *CandleChunk) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *CandleChunk) GetCandles() []*Candle {
	if m != nil {
		return m.Candles
	}
	return nil
}

type CandleChunkList struct {
	KeyIDs               []string `protobuf:"bytes,1,rep,name=keyIDs,proto3" json:"keyIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandleChunkList) Reset()         { *m = CandleChunkList{} }
func (m *CandleChunkList) String() string { return proto.CompactTextString(m) }
func (*CandleChunkList) ProtoMessage()    {}
func (*CandleChunkList) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{2}
}
func (m *CandleChunkList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandleChunkList.Unmarshal(m, b)
}
func (m *CandleChunkList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandleChunkList.Marshal(b, m, deterministic)
}
func (dst *CandleChunkList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandleChunkList.Merge(dst, src)
}
func (m *CandleChunkList) XXX_Size() int {
	return xxx_messageInfo_CandleChunkList.Size(m)
}
func (m *CandleChunkList) XXX_DiscardUnknown() {
	xxx_messageInfo_CandleChunkList.DiscardUnknown(m)
}

var xxx_messageInfo_CandleChunkList proto.InternalMessageInfo

func (m *CandleChunkList) GetKeyIDs() []string {
	if m != nil {
		return m.KeyIDs
	}
	return nil
}

type Order struct {
	OrderID              string    `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	OrderType            ORDERTYPE `protobuf:"varint,2,opt,name=orderType,proto3,enum=tradingdb.ORDERTYPE" json:"orderType,omitempty"`
	OrderSide            ORDERSIDE `protobuf:"varint,3,opt,name=orderSide,proto3,enum=tradingdb.ORDERSIDE" json:"orderSide,omitempty"`
	Price                int64     `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Volume               int64     `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	StartTime            int64     `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	AvgPrice             int64     `protobuf:"varint,7,opt,name=avgPrice,proto3" json:"avgPrice,omitempty"`
	DoneVolume           int64     `protobuf:"varint,8,opt,name=doneVolume,proto3" json:"doneVolume,omitempty"`
	DoneTime             int64     `protobuf:"varint,9,opt,name=doneTime,proto3" json:"doneTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{3}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetOrderType() ORDERTYPE {
	if m != nil {
		return m.OrderType
	}
	return ORDERTYPE_INVALIDTYPE
}

func (m *Order) GetOrderSide() ORDERSIDE {
	if m != nil {
		return m.OrderSide
	}
	return ORDERSIDE_INVALID_ORDERSIDE
}

func (m *Order) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Order) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Order) GetAvgPrice() int64 {
	if m != nil {
		return m.AvgPrice
	}
	return 0
}

func (m *Order) GetDoneVolume() int64 {
	if m != nil {
		return m.DoneVolume
	}
	return 0
}

func (m *Order) GetDoneTime() int64 {
	if m != nil {
		return m.DoneTime
	}
	return 0
}

type Trade struct {
	TradeID              string   `protobuf:"bytes,1,opt,name=tradeID,proto3" json:"tradeID,omitempty"`
	OrderID              string   `protobuf:"bytes,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	CurTime              int64    `protobuf:"varint,3,opt,name=curTime,proto3" json:"curTime,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Volume               int64    `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{4}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (dst *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(dst, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetTradeID() string {
	if m != nil {
		return m.TradeID
	}
	return ""
}

func (m *Trade) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trade) GetCurTime() int64 {
	if m != nil {
		return m.CurTime
	}
	return 0
}

func (m *Trade) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type TradingData struct {
	KeyID                string   `protobuf:"bytes,1,opt,name=keyID,proto3" json:"keyID,omitempty"`
	Orders               []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Trades               []*Trade `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradingData) Reset()         { *m = TradingData{} }
func (m *TradingData) String() string { return proto.CompactTextString(m) }
func (*TradingData) ProtoMessage()    {}
func (*TradingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{5}
}
func (m *TradingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradingData.Unmarshal(m, b)
}
func (m *TradingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradingData.Marshal(b, m, deterministic)
}
func (dst *TradingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradingData.Merge(dst, src)
}
func (m *TradingData) XXX_Size() int {
	return xxx_messageInfo_TradingData.Size(m)
}
func (m *TradingData) XXX_DiscardUnknown() {
	xxx_messageInfo_TradingData.DiscardUnknown(m)
}

var xxx_messageInfo_TradingData proto.InternalMessageInfo

func (m *TradingData) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *TradingData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *TradingData) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type MarketTradeData struct {
	MsTime               int64     `protobuf:"varint,1,opt,name=msTime,proto3" json:"msTime,omitempty"`
	Price                int64     `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume               int64     `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Side                 TRADESIDE `protobuf:"varint,4,opt,name=side,proto3,enum=tradingdb.TRADESIDE" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MarketTradeData) Reset()         { *m = MarketTradeData{} }
func (m *MarketTradeData) String() string { return proto.CompactTextString(m) }
func (*MarketTradeData) ProtoMessage()    {}
func (*MarketTradeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{6}
}
func (m *MarketTradeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketTradeData.Unmarshal(m, b)
}
func (m *MarketTradeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketTradeData.Marshal(b, m, deterministic)
}
func (dst *MarketTradeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketTradeData.Merge(dst, src)
}
func (m *MarketTradeData) XXX_Size() int {
	return xxx_messageInfo_MarketTradeData.Size(m)
}
func (m *MarketTradeData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketTradeData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketTradeData proto.InternalMessageInfo

func (m *MarketTradeData) GetMsTime() int64 {
	if m != nil {
		return m.MsTime
	}
	return 0
}

func (m *MarketTradeData) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MarketTradeData) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *MarketTradeData) GetSide() TRADESIDE {
	if m != nil {
		return m.Side
	}
	return TRADESIDE_INVALID_TRADESIDE
}

type MarketContractData struct {
	CategoryCode         string   `protobuf:"bytes,1,opt,name=categoryCode,proto3" json:"categoryCode,omitempty"`
	ContractCode         string   `protobuf:"bytes,2,opt,name=contractCode,proto3" json:"contractCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketContractData) Reset()         { *m = MarketContractData{} }
func (m *MarketContractData) String() string { return proto.CompactTextString(m) }
func (*MarketContractData) ProtoMessage()    {}
func (*MarketContractData) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{7}
}
func (m *MarketContractData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketContractData.Unmarshal(m, b)
}
func (m *MarketContractData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketContractData.Marshal(b, m, deterministic)
}
func (dst *MarketContractData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketContractData.Merge(dst, src)
}
func (m *MarketContractData) XXX_Size() int {
	return xxx_messageInfo_MarketContractData.Size(m)
}
func (m *MarketContractData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketContractData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketContractData proto.InternalMessageInfo

func (m *MarketContractData) GetCategoryCode() string {
	if m != nil {
		return m.CategoryCode
	}
	return ""
}

func (m *MarketContractData) GetContractCode() string {
	if m != nil {
		return m.ContractCode
	}
	return ""
}

type MarketCategoryData struct {
	CategoryCode         string                `protobuf:"bytes,1,opt,name=categoryCode,proto3" json:"categoryCode,omitempty"`
	Contracts            []*MarketContractData `protobuf:"bytes,2,rep,name=contracts,proto3" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MarketCategoryData) Reset()         { *m = MarketCategoryData{} }
func (m *MarketCategoryData) String() string { return proto.CompactTextString(m) }
func (*MarketCategoryData) ProtoMessage()    {}
func (*MarketCategoryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{8}
}
func (m *MarketCategoryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketCategoryData.Unmarshal(m, b)
}
func (m *MarketCategoryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketCategoryData.Marshal(b, m, deterministic)
}
func (dst *MarketCategoryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketCategoryData.Merge(dst, src)
}
func (m *MarketCategoryData) XXX_Size() int {
	return xxx_messageInfo_MarketCategoryData.Size(m)
}
func (m *MarketCategoryData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketCategoryData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketCategoryData proto.InternalMessageInfo

func (m *MarketCategoryData) GetCategoryCode() string {
	if m != nil {
		return m.CategoryCode
	}
	return ""
}

func (m *MarketCategoryData) GetContracts() []*MarketContractData {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type MarketData struct {
	MarketCode           string                `protobuf:"bytes,1,opt,name=marketCode,proto3" json:"marketCode,omitempty"`
	Categories           []*MarketCategoryData `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MarketData) Reset()         { *m = MarketData{} }
func (m *MarketData) String() string { return proto.CompactTextString(m) }
func (*MarketData) ProtoMessage()    {}
func (*MarketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_trading_f664a5e987fbfa61, []int{9}
}
func (m *MarketData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketData.Unmarshal(m, b)
}
func (m *MarketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketData.Marshal(b, m, deterministic)
}
func (dst *MarketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketData.Merge(dst, src)
}
func (m *MarketData) XXX_Size() int {
	return xxx_messageInfo_MarketData.Size(m)
}
func (m *MarketData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketData proto.InternalMessageInfo

func (m *MarketData) GetMarketCode() string {
	if m != nil {
		return m.MarketCode
	}
	return ""
}

func (m *MarketData) GetCategories() []*MarketCategoryData {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*Candle)(nil), "tradingdb.Candle")
	proto.RegisterType((*CandleChunk)(nil), "tradingdb.CandleChunk")
	proto.RegisterType((*CandleChunkList)(nil), "tradingdb.CandleChunkList")
	proto.RegisterType((*Order)(nil), "tradingdb.Order")
	proto.RegisterType((*Trade)(nil), "tradingdb.Trade")
	proto.RegisterType((*TradingData)(nil), "tradingdb.TradingData")
	proto.RegisterType((*MarketTradeData)(nil), "tradingdb.MarketTradeData")
	proto.RegisterType((*MarketContractData)(nil), "tradingdb.MarketContractData")
	proto.RegisterType((*MarketCategoryData)(nil), "tradingdb.MarketCategoryData")
	proto.RegisterType((*MarketData)(nil), "tradingdb.MarketData")
	proto.RegisterEnum("tradingdb.ORDERTYPE", ORDERTYPE_name, ORDERTYPE_value)
	proto.RegisterEnum("tradingdb.ORDERSIDE", ORDERSIDE_name, ORDERSIDE_value)
	proto.RegisterEnum("tradingdb.TRADESIDE", TRADESIDE_name, TRADESIDE_value)
}

func init() { proto.RegisterFile("trading.proto", fileDescriptor_trading_f664a5e987fbfa61) }

var fileDescriptor_trading_f664a5e987fbfa61 = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6b, 0xdb, 0x4a,
	0x14, 0x8d, 0x24, 0x5b, 0x89, 0xae, 0xf3, 0xa1, 0x0c, 0x79, 0x61, 0x78, 0xbc, 0x17, 0x8c, 0x36,
	0xcf, 0x2f, 0x85, 0x2c, 0xd2, 0x65, 0xe9, 0x22, 0xb5, 0xbc, 0x10, 0x38, 0x4d, 0x98, 0xa8, 0x81,
	0x40, 0x21, 0x28, 0xd2, 0xe0, 0x08, 0xdb, 0x92, 0x91, 0xe4, 0x84, 0x2c, 0x4b, 0x7f, 0x4f, 0xa1,
	0xbf, 0xa6, 0xbf, 0xa7, 0xcc, 0x9d, 0x91, 0x34, 0x6a, 0x42, 0x49, 0x77, 0x73, 0xce, 0x9c, 0xfb,
	0x71, 0xee, 0x5c, 0x21, 0xd8, 0xa9, 0x8a, 0x28, 0x49, 0xb3, 0xd9, 0xc9, 0xaa, 0xc8, 0xab, 0x9c,
	0x38, 0x0a, 0x26, 0x77, 0xde, 0x0f, 0x03, 0xec, 0x71, 0x94, 0x25, 0x0b, 0x4e, 0x08, 0xf4, 0xe2,
	0x3c, 0xe1, 0xd4, 0x18, 0x1a, 0x23, 0x87, 0xe1, 0x59, 0x70, 0x59, 0xb4, 0xe4, 0xd4, 0x94, 0x9c,
	0x38, 0x0b, 0x2e, 0x5f, 0xf1, 0x8c, 0x5a, 0x43, 0x63, 0x64, 0x31, 0x3c, 0x93, 0x03, 0xe8, 0xc7,
	0x8b, 0xbc, 0xe4, 0xb4, 0x87, 0xa4, 0x04, 0x42, 0x79, 0x9f, 0xce, 0xee, 0x69, 0x5f, 0x2a, 0xc5,
	0x99, 0xb8, 0x60, 0x2d, 0xf2, 0x47, 0x6a, 0x23, 0x25, 0x8e, 0x84, 0xc2, 0x66, 0xbc, 0x2e, 0xc2,
	0x74, 0xc9, 0xe9, 0x26, 0xb2, 0x35, 0x24, 0x87, 0x60, 0x3f, 0xe4, 0x8b, 0xf5, 0x92, 0xd3, 0x2d,
	0xbc, 0x50, 0x88, 0x78, 0xb0, 0x2d, 0xaa, 0x06, 0x59, 0xc5, 0x0b, 0x5e, 0x56, 0xd4, 0xc1, 0xdb,
	0x0e, 0xe7, 0x7d, 0x37, 0x60, 0x20, 0x8d, 0x8d, 0xef, 0xd7, 0xd9, 0xfc, 0xd5, 0xee, 0xfe, 0x01,
	0xa7, 0xac, 0xa2, 0xa2, 0xc2, 0x7e, 0xa4, 0xc5, 0x96, 0x10, 0xbd, 0xf2, 0x2c, 0xc1, 0x3b, 0xe9,
	0xb4, 0x86, 0x62, 0x02, 0x73, 0xfe, 0x14, 0xf8, 0x68, 0xd6, 0x61, 0x12, 0x90, 0x37, 0xb0, 0x19,
	0x63, 0x13, 0x25, 0xb5, 0x87, 0xd6, 0x68, 0x70, 0xba, 0x7f, 0xd2, 0xcc, 0xfe, 0x44, 0xb6, 0xc7,
	0x6a, 0x85, 0xf7, 0x3f, 0xec, 0x69, 0x1d, 0x4f, 0xd3, 0xb2, 0x12, 0x13, 0xc0, 0x44, 0x25, 0x35,
	0x86, 0xd6, 0xc8, 0x61, 0x0a, 0x79, 0xdf, 0x4c, 0xe8, 0x5f, 0x14, 0x09, 0x2f, 0x44, 0x47, 0xb9,
	0x38, 0x04, 0xbe, 0xb2, 0x56, 0x43, 0x72, 0x0a, 0x0e, 0x1e, 0xc3, 0xa7, 0x95, 0xb4, 0xb8, 0x7b,
	0x7a, 0xa0, 0x55, 0xbf, 0x60, 0xfe, 0x84, 0x85, 0x37, 0x97, 0x13, 0xd6, 0xca, 0x9a, 0x98, 0xab,
	0x34, 0x91, 0xee, 0x5f, 0x88, 0xb9, 0x0a, 0xfc, 0x3a, 0x46, 0xc8, 0x84, 0xf3, 0x55, 0x91, 0xc6,
	0xcd, 0xdb, 0x23, 0xd0, 0xde, 0xae, 0xdf, 0x79, 0xbb, 0xce, 0x7c, 0xed, 0x5f, 0xe7, 0xfb, 0x37,
	0x6c, 0x45, 0x0f, 0xb3, 0x4b, 0x4c, 0x27, 0x97, 0xa1, 0xc1, 0xe4, 0x08, 0x20, 0xc9, 0x33, 0x7e,
	0xad, 0x6f, 0x84, 0xc6, 0x88, 0x58, 0x81, 0x30, 0xb1, 0xdc, 0x88, 0x06, 0x7b, 0x5f, 0x0d, 0xe8,
	0x87, 0x45, 0x94, 0xe0, 0x0b, 0x0a, 0x3f, 0xbc, 0x9d, 0x97, 0x82, 0xfa, 0x24, 0xcd, 0xee, 0x24,
	0xb5, 0x0d, 0xb5, 0xba, 0x1b, 0xfa, 0x47, 0xde, 0xbd, 0x47, 0x18, 0x84, 0x72, 0x96, 0x7e, 0x54,
	0x45, 0xed, 0xca, 0x18, 0xfa, 0xca, 0x8c, 0xc0, 0xc6, 0xba, 0x25, 0x35, 0x71, 0x63, 0x5c, 0x7d,
	0xfe, 0xe2, 0x82, 0xa9, 0x7b, 0xa1, 0xc4, 0xde, 0x4b, 0x6a, 0x3d, 0x53, 0xa2, 0x59, 0xa6, 0xee,
	0xbd, 0x2f, 0x06, 0xec, 0x9d, 0x47, 0xc5, 0x9c, 0x57, 0xc8, 0x63, 0xf5, 0x43, 0xb0, 0x97, 0x25,
	0x7a, 0x32, 0x64, 0x93, 0x12, 0xb5, 0x96, 0xcc, 0x97, 0x2d, 0x59, 0x9d, 0xe7, 0x1c, 0x41, 0xaf,
	0x14, 0xbb, 0xd2, 0x7b, 0xb6, 0x2b, 0x21, 0x3b, 0xf3, 0x27, 0xb8, 0x2b, 0xa8, 0xf0, 0x3e, 0x03,
	0x91, 0x2d, 0x8c, 0xf3, 0xac, 0x2a, 0xa2, 0xb8, 0xc2, 0x2e, 0x3c, 0xd8, 0x8e, 0xa3, 0x8a, 0xcf,
	0xf2, 0xe2, 0x69, 0xdc, 0x7e, 0x9e, 0x1d, 0x0e, 0x35, 0x2a, 0x06, 0x35, 0xa6, 0xd2, 0x68, 0x9c,
	0xb7, 0x6e, 0xb2, 0xab, 0xc8, 0x57, 0x67, 0x7f, 0x07, 0x4e, 0x9d, 0xa9, 0x1e, 0xf9, 0xbf, 0x9a,
	0x8d, 0xe7, 0x3d, 0xb3, 0x56, 0xef, 0xcd, 0x01, 0xa4, 0x00, 0xcb, 0x1d, 0x01, 0x2c, 0x95, 0xbc,
	0x29, 0xa6, 0x31, 0xe4, 0x3d, 0x80, 0x2a, 0x9d, 0xf2, 0xdf, 0xd4, 0xd2, 0x1c, 0x30, 0x2d, 0xe0,
	0xf8, 0x3f, 0x70, 0x9a, 0x8f, 0x96, 0xec, 0xc1, 0x20, 0xf8, 0x78, 0x7d, 0x36, 0x0d, 0x7c, 0x01,
	0xdd, 0x0d, 0xe2, 0x40, 0x7f, 0x1a, 0x9c, 0x07, 0xa1, 0x6b, 0x1c, 0x9f, 0x29, 0xa1, 0x98, 0x3e,
	0xf9, 0x0b, 0xf6, 0x95, 0xf0, 0xb6, 0x21, 0xdd, 0x0d, 0xb2, 0xa3, 0x34, 0xb7, 0x1f, 0x3e, 0xdd,
	0xb8, 0x06, 0xd9, 0x05, 0x90, 0xf0, 0x6a, 0x32, 0x9d, 0xba, 0xa6, 0x48, 0xd1, 0x3c, 0xa0, 0x9e,
	0xa2, 0x21, 0x65, 0x0a, 0x84, 0x6d, 0x0a, 0x09, 0x65, 0x8a, 0x3b, 0x1b, 0x7f, 0x36, 0x6f, 0x7f,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x71, 0x64, 0x50, 0x7d, 0x06, 0x00, 0x00,
}
